### ISSUE TITLE
Review Projet

### ISSUE THREAD

**Issue by NicolasGlassey** [CPNV-ES-MAS3-X/Prometheus-Containerization#14]
## Introduction

Je tiens à vous féliciter pour vos livrables. La couverture fonctionnelles a pratiquement été atteinte par toute les devopsteams.

## Review générale

Ce chapitre regroupe les éléments que j'ai retrouvés chez plusieurs devopsteams. Plusieurs points mentionnés ici n'ont pas eu d'impact sur votre note de module, mais c'est ainsi que je vous donne, aussi, des pistes pour la suite.

* Les systèmes générant des logs (dès qu'il y a des services) sont prolifiques. C'est une problématique que vous devez solutionner dès le début du projet. Mettre en place des [rotations de logs](https://httpd.apache.org/docs/2.4/programs/rotatelogs.html) est essentiel.
* Schéma d'infrastructure. 
    * Pensez à bien indiquer le sens de communication entre vos différentes couches. Dans le cas d'un [firewall statefull](https://www.baeldung.com/cs/firewalls-stateless-vs-stateful) ceci est essentiel.
    * Eviter de mentionner plusieurs fois la même information sur le schéma. Lors de la première mise à jour vous risquez des incohérences.
* Sourcez vos documents. Mentionnez un fait, une valeur reprise d'un site et de ne pas mentionner la source et légalement plus que limite. Mais au-delà de cela, d'un point de vue ethique ne le fait pas. Nombreuses pages de vos wikis sont très bien sourcées, puis certains éléments plus du tout. Attention.
* Versionnez vos documents. Rien de tel pour travailler en équipe avec les bons documents. Dans ce cas là je pense non seulement à votre schéma d'infrastucture, mais aussi à vos codes. Vous avez intégré dans votre wiki parfois des scripts, des templates d'email, des configurations d'agent. Ceci doit être dans le dépôt -code- (excepté le schéma).

## Fonctionnalités

Comme son nom l'indique, ce chapite ne se concentre uniquement et que sur les fonctionnalités (démontrées en démo).

Note : si ne me mentionne rien, c'est que vous avez atteint l'objectif.

- [x] Accès au dashboard
* La mise en place du login sur le Dashboard est maîtrisée par la team. Mais les conséquences sur les mécanismes d'authentification des autres composants ne l'est pas encore.
* La démonstration se fait (sans login)[https://github.com/CPNV-MON1/Prometheus/issues/9].

- [x] Lister les hôtes
* L'aspect est un peu rustique. Ceci est lié à l'approche favorisé par Prometheus et Grafana qui ne proposent pas de Dashboard aussi bien soigné que les autres produits de monitoring.

- [x] Récupérer les métriques de base (CPU/RAM/DD)

- [x] Superviser l'état de services

- [x] Alerter les différents publiques

- [x] Agir de manière automatique sur les hôtes (uniquement pour une service hébergé sur le client Linux)

## Clean infra

Ce chapitre a pour but d'évaluer la "propreté" de votre livrable.

- [x] Etat des logs après un redémarrage

- [x] Sécurité
Note : j'ai allégé ce critère. L'idée était de valoriser un fonctionnelment correcte en appliquant **stricto sensos** les règles de sécurité les plus restreints. Ceci demandait un temps d'analyse plus important que ne le permettait la démonstration. J'ai gardé uniquement le critère d'identification des ports et protocoel et leur mention dans le schéma. On validera cela ensemble une fois "dockerisé".
* Un point étonnant, lorsque l'on coupe toutes possiblité aux agents de communiquer au sein du sous-réseau privé, les métriques continuer d'être reçus. Ceci sera étudié en MAS lorsque nous continuerons le projet en le dockerisant.

## Transmissibilité
L'idée de prendre un projet et de le mettre à la poublelle m'aggace profondément. J'évalue donc la qualité de vos schémas, wiki et issues pour voir si une reprise de votre projet est envisageable. Ce qui tombe bien, vu que vous allez effectivement reprendre ce projet pour MAS en deuxième année.

- [x] Schéma de l'infra
* Manque le sens du flux.
* Les informations sont répétées (risque d'incohérence).

- [x] Choix de la solution
* Il n'y a pas plusieurs version de Prometheus (d'un point de vue architecturelle oui, mais pas des fonctionnalités), c'est normal que la team ne justifie pas son choix.

- [x] Licence
* Une seule licence est mise en évidence. Vous auriez dû mettre en évidence la palette de licence pour chacun des composants.

- [x] Dimensionnement de l'infra
* Ce point n'est pas traité. L'approche Prometheus n'est pas classique et il est normal qu'il ne vous offre pas de tabelles comme certains autres produits. Mais du coup comment faire pour adapter l'infra par rapport à la charge. Voici le genre de [pistes](https://tech.trivago.com/post/2022-08-23-how-we-scaled-our-prometheus-setup.html) que vous auriez pu lire et vous appuyer pour argumenter (même briévement).

- [x] Lien avec la documentation officielle
* Lorsqu'il s'agit de mise en place, vous avez bien mentionné vos sources.
* Pour les pages "Debug/Dépannage/Choix du produit" on se retrouve à devoir les re-chercher. Dommage.

- [x] Soin, niveau de finition de la documentation
* Gros job.
* Pensez à imaginer une structure plus simple, voir un chapitre "en bref" pour faciliter la prise en main. Une sorte de starter kit. (librenms a fait une version de ce genre, à réfléchir).

- [x] Issues - référencement des disfonctionnements ou des fonctionnalités qui ne donnent pas satisfaction
* La systèmatique semble être là. On travaillera encore la structure de l'issue pour gagner en efficacité dans les prochains modules.

## Votre évaluation

* Note du projet : 5.50
* Note personnelle
    * Bassi Luca : 6.00 (je tiens à valoriser votre rôle de co-leader dans le projet)
    * Grossenbacher Yann : 6.00 (je tiens à valoriser votre rôle de co-leader dans le projet)
    * Roulet David : 5.50 (la prochaine, on fonce ensemble ok ?)

**Comment by Enelg52** [comment]
Close fin du projet
