### ISSUE TITLE
Emails AWS Creds

### ISSUE THREAD

**Issue by LucaBassi** [CPNV-ES-MAS3-X/Prometheus-Containerization#15]
@NicolasGlassey 
Prometheus team need AWS emails account credentials 
fields needed :  
```
 smarthost: email-smtp.eu-central-1.amazonaws.com:587  
 auth_username: ''  
 auth_identity: ''  
 auth_password: ''  
```

**Comment by NicolasGlassey** [comment]
No storie requires an email to be sent. To notify both end-users and technical support I ask you to work with webhooks.

I'd be happy to supply you with smtp data, but I don't want you to waste time setting this up.

Please confirm the requirement again.

**Comment by LucaBassi** [comment]
If email configuration is not required in next steps of the project we don't need smtp crendentials.

All others features, webhooks and social media, are already done in our local infrastructure.

I let to you close de issue if email confif is not required in the futur.

**Comment by LucaBassi** [comment]
@NicolasGlassey 

If email configuration is not required in next steps of the project we don't need smtp crendentials.

All others features, webhooks and social media, are already done in our local infrastructure.

I let to you close de issue if email confif is not required in the futur.

**Comment by LucaBassi** [comment]
@NicolasGlassey

If email configuration is not required in next steps of the project we don't need smtp crendentials.

All others features, webhooks and social media, are already done in our local infrastructure.

I let to you close de issue if email config is not required in the futur.
