### ISSUE TITLE
AWS Timestream

### ISSUE THREAD

**Issue by NicolasGlassey** [CPNV-ES-MAS3-X/Prometheus-Containerization#22]
Voici pour valider les accès au service TimeStream

```
[INPUT]
aws timestream-query describe-endpoints \
 --profil MAS_PROMETHEUS \
 --region us-west-2

[OUTPUT]
{
    "Endpoints": [
        {
            "Address": "query-cell1.timestream.us-west-2.amazonaws.com",
            "CachePeriodInMinutes": 1440
        }
    ]
}
```

Les crédentials sont dans le groupe teams.

**Comment by NicolasGlassey** [comment]
et voilà une première query de type select

```
[INPUT]
aws timestream-query query --query-string "SELECT * FROM prometheus.DevOps where time >= ago (15m)" --endpoint-url https://query-cell1.timestream.us-west-2.amazonaws.com --profile MAS_PROMETHEUS --region us-west-2

[OUTPUT]
{
    "Rows": [],
    "ColumnInfo": [
        {
            "Name": "hostname",
            "Type": {
                "ScalarType": "VARCHAR"
            }
        },
        {
            "Name": "az",
            "Type": {
                "ScalarType": "VARCHAR"
            }
        },
        {
            "Name": "region",
            "Type": {
                "ScalarType": "VARCHAR"
            }
        },
        {
            "Name": "measure_name",
            "Type": {
                "ScalarType": "VARCHAR"
            }
        },
        {
            "Name": "time",
            "Type": {
                "ScalarType": "TIMESTAMP"
            }
        },
        {
            "Name": "measure_value::double",
            "Type": {
                "ScalarType": "DOUBLE"
            }
        }
    ],
    "QueryId": "AEDACANQ5NSJHNXNQDYJ6D7MXR7TMCD5HXXLPII7SPHFDK4WWAX6WWTU6WSTXBQ",
    "QueryStatus": {
        "ProgressPercentage": 100.0,
        "CumulativeBytesScanned": 0,
        "CumulativeBytesMetered": 10000000
    }
}
````

**Comment by LucaBassi** [comment]
@NicolasGlassey 

Voici les permissions que nous avons besoins sur la DB AWS :
(la "Ressource" est encore à adapter, je n'ai pas réussis à la trouver avec le Cli AWS)
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowReadWriteToTable",
            "Effect": "Allow",
            "Action": [
                "timestream:WriteRecords",
                "timestream:Select"
            ],
            "Resource": "arn:aws:timestream:region:AccoundId:database/DatabaseName/table/TableName"
        },
        {
            "Sid": "AllowDescribeEndpoints",
            "Effect": "Allow",
            "Action": "timestream:DescribeEndpoints",
            "Resource": "*"
        },
        {
            "Sid": "AllowValueRead",
            "Effect": "Allow",
            "Action": "timestream:SelectValues",
            "Resource": "*"
        }
    ]
}`

Nous avons aussi besoins d'une URL et d'un port ou aller lire et écrire sur la DB AWS
Est-ce celle ci ? : `query-cell1.timestream.us-west-2.amazonaws.com:9201` 

Url ou nous irions lire et écrire : 
`http://query-cell1.timestream.us-west-2.amazonaws.com:9201:9201/write`
`http://query-cell1.timestream.us-west-2.amazonaws.com:9201:9201/read`

**Comment by NicolasGlassey** [comment]
@Enelg52 @LucaBassi  

J'ai amélioré la synthaxe des commandes livrées hier (pour windows, remplace \ par ^).

Je traite à l'instant votre demande d'accès. En espérant y arriver pour la session de cet après-midi.

A+

**Comment by NicolasGlassey** [comment]
@Enelg52  @LucaBassi 

Voici la policy que j'ai mise en place.

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowReadWriteToTable",
            "Effect": "Allow",
            "Action": [
                "timestream:WriteRecords",
                "timestream:Select"
            ],
            "Resource": "arn:aws:timestream:us-west-2:709024702237:database/prometheus/table/DevOps"
        },
        {
            "Sid": "AllowDescribeEndpoints",
            "Effect": "Allow",
            "Action": "timestream:DescribeEndpoints",
            "Resource": "*"
        },
        {
            "Sid": "AllowValueRead",
            "Effect": "Allow",
            "Action": "timestream:SelectValues",
            "Resource": "*"
        },
        {
            "Sid": "AllowDescribeTable",
            "Effect": "Allow",
            "Action": "timestream:DescribeTable",
            "Resource": "*"
        }
    ]
}

**Comment by NicolasGlassey** [comment]
@LucaBassi  @Enelg52 

Et voilà les commandes que j'ai pu réaliser avec succès::

```
[INPUT]
aws timestream-query describe-endpoints \
--profile MAS_PROMETHEUS \
--region us-west-2

[OUPUT]
{
    "Endpoints": [
        {
            "Address": "query-cell1.timestream.us-west-2.amazonaws.com",
            "CachePeriodInMinutes": 1440
        }
    ]
}
```

```
[INPUT]
aws timestream-query query \
--query-string \
    "SELECT * 
    FROM prometheus.DevOps 
    WHERE time >= ago (15m)" \
--endpoint-url https://query-cell1.timestream.us-west-2.amazonaws.com \
--profile MAS_PROMETHEUS \
--region us-west-2
[OUTPUT]
///table content in json
```

```

**Comment by NicolasGlassey** [comment]
@LucaBassi  @Enelg52 

Et voilà où j'en suis... 

```
[INPUT]
aws timestream-write write-records \
--database-name prometheus \
--table-name DevOps \
--common-attributes "{\"Dimensions\":[{\"Name\":\"hostname\", \"Value\":\"WIN_MON_CLI\"}], \"Time\":\"1631051324000\",\"TimeUnit\":\"MILLISECONDS\"}" \
--records "[{\"MeasureName\":\"CPU Consumption\", \"MeasureValueType\":\"DOUBLE\",\"MeasureValue\":\"30\"}]" \
--endpoint-url https://query-cell1.timestream.us-west-2.amazonaws.com \
--profile MAS_PROMETHEUS \
--region us-west-2 \
--debug

[OUTPUT]
/// internal error with debug content
```

**Comment by NicolasGlassey** [comment]
@LucaBassi  @Enelg52 

Voici le schéma de la table

![image](https://github.com/CPNV-ES-MAS3-X/Prometheus-Containerization/assets/5616312/c8a054b7-7ab9-4822-bc0b-37caca4cefd1)

**Comment by LucaBassi** [comment]
@NicolasGlassey 

Il nous manque quelques info a propos du compte AWS :
- <name of account>
- <accountID> ( qui n'est pas "access_key" il me semble )

**Comment by Enelg52** [comment]
On utilise plutôt influxdb
