### ISSUE TITLE
Demande de nouvelle de machine (Docker - InfluxDB)

### ISSUE THREAD

**Issue by LucaBassi** [CPNV-ES-MAS3-X/Prometheus-Containerization#23]
Nouvelle machine nécessaire sur AWS

### Machine
OS : Debian 12
Nb Proc : 2
RAM : 4 Go
Disque : 5 Go  

### Firewall
l'ouverture du port UDP 8086 est nécessaire en Inbound sur cette machine

**Comment by NicolasGlassey** [comment]
@LucaBassi 

L'instance est prête est atteignable.

* Vous trouverez les informations de connection sur le partage one drive. J'ai valider la connection string ainsi que la clé.

* Validation de l'accès au web

```bash
sudo apt update
Get:1 file:/etc/apt/mirrors/debian.list Mirrorlist [38 B]
Get:2 file:/etc/apt/mirrors/debian-security.list Mirrorlist [47 B]
Hit:3 https://cdn-aws.deb.debian.org/debian bookworm InRelease
Hit:4 https://cdn-aws.deb.debian.org/debian bookworm-updates InRelease
Hit:5 https://cdn-aws.deb.debian.org/debian bookworm-backports InRelease
Hit:6 https://cdn-aws.deb.debian.org/debian-security bookworm-security InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
27 packages can be upgraded. Run 'apt list --upgradable' to see them.
```

Je vous confirme que j'ai appliqué une règle de sécurité bien "large" sur cette instance. Tous les protocoles, tous les ports, en provenance du sous-réseau 10.0.4.0/24.
